# Code auto-generated by UCC

.data

.str0:	.string	"How are you?\012"
.str1:	.string	"Fine, thank you.\012"
.str2:	.string	"Fine\012"
.str3:	.string	"How are you?Fine, thank you.\012"
.str4:	.string	"Hello,World\012"


.align 4
.globl	num

num:	.long	45

.globl	string0

string0:	.long	.str0

.globl	string1

string1:	.long	.str1

.globl	string2

string2:	.long	.str2

.globl	string3

string3:	.long	.str3


.text

.globl	max

max:
	pushl %ebp
	pushl %ebx
	pushl %esi
	pushl %edi
	movl %esp, %ebp
	subl $24, %esp
.BB0:
	leal .str4, %eax
	movl %eax, -4(%ebp)
	movl -4(%ebp), %ecx
	movl %ecx, -8(%ebp)
	movl $100, -12(%ebp)
	movl $200, -16(%ebp)
	movl -12(%ebp), %ecx
	addl -16(%ebp), %ecx
	movl %ecx, num
	movl num, %eax
	movl %ebp, %esp
	popl %edi
	popl %esi
	popl %ebx
	popl %ebp
	ret

.globl	main

main:
	pushl %ebp
	pushl %ebx
	pushl %esi
	pushl %edi
	movl %esp, %ebp
	subl $28, %esp
.BB1:
	movl num, %eax
	movl %eax, -4(%ebp)
	movl $5, -8(%ebp)
	pushl -8(%ebp)
	pushl -4(%ebp)
	call max
	addl $8, %esp
	movl %eax, -12(%ebp)
	movl num, %eax
	movl %eax, -16(%ebp)
	movl -12(%ebp), %eax
	subl -16(%ebp), %eax
	movl %eax, -20(%ebp)
	movl -20(%ebp), %ecx
	addl $2, %ecx
	movl %ecx, -20(%ebp)
	movl -20(%ebp), %eax
	movl %ebp, %esp
	popl %edi
	popl %esi
	popl %ebx
	popl %ebp
	ret

