#ifndef OPCODE
#error "You must define OPCODE macro before include this file"
#endif
// enum {ADDR,DEREF,ADD,MOV,CALL,JMP,JZ,JNZ,JE,JNE,JL,JLE,JG,JGE,DEC, INC, RET, NOP}
// OPCODE(MOV, "=",  Move)
// OPCODE(NOP, "+=",  Assignment)
// OPCODE(NOP, "-=",  Assignment)
// OPCODE(NOP, "|=",  Assignment)
// OPCODE(NOP, "^=",  Assignment)
// OPCODE(NOP, "*=",  Assignment)
// OPCODE(NOP, "/=",  Assignment)
// OPCODE(NOP, "%=",  Assignment)
// OPCODE(NOP, "<<=",  Assignment)
// OPCODE(NOP, ">>=",  Assignment)
// OPCODE(NOP, "&=",  Assignment)
// OPCODE(NOP, "&^=",  Assignment)
// OPCODE(NOP, ":=",  Assignment)

// OPCODE(NOP, "||",  Binary)
// OPCODE(NOP, "&&",  Binary)
// OPCODE(BOR, "|",  Binary)
// OPCODE(BXOR, "^",  Binary)
// OPCODE(BAND, "&",  Binary)
// OPCODE(LSF, "<<",  Binary)
// OPCODE(RSF, ">>",  Binary)
// OPCODE(ADD, "+",  Assignment)
// OPCODE(SUB, "-",  Binary)
// OPCODE(MUL, "*",  Binary)
// OPCODE(DIV, "/",  Binary)
// OPCODE(MOD, "%",  Binary)
// OPCODE(NEG, "-",  Binary)
// OPCODE(BCOM,    "~",                    Assign)

OPCODE(BOR, "|",  Assignment)
OPCODE(BXOR, "^",  Assignment)
OPCODE(BAND, "&",  Assignment)
OPCODE(LSF, "<<",  Assignment)
OPCODE(RSF, ">>",  Assignment)
OPCODE(ADD, "+",  Assignment)
OPCODE(SUB, "-",  Assignment)
OPCODE(MUL, "*",  Assignment)
OPCODE(DIV, "/",  Assignment)
OPCODE(MOD, "%",  Assignment)
OPCODE(NEG, "-",  Assignment)
// OPCODE(BCOM,    "~",Assignment)
OPCODE(BCOM,    "^",Assignment)

// OPCODE(JE, "==",  Binary)
// OPCODE(JNE, "!=",  Binary)
OPCODE(JE, "==",  Branch)
OPCODE(JNE, "!=",  Branch)
OPCODE(JZ,      "",                     Branch)
OPCODE(JNZ, "!",  Branch)
OPCODE(JG, ">",  Binary)
OPCODE(JL, "<",  Binary)
OPCODE(JGE, ">=",  Binary)
OPCODE(JLE, "<=",  Binary)

// OPCODE(NOP, "&^",  Binary)

// OPCODE(NOP, "<-",  Assignment)


// OPCODE(NOP, "+",  Unary)
// OPCODE(NOP, "-",  Unary)
// OPCODE(NOP, "^",  Unary)
OPCODE(DEREF, "*",  Deref)
OPCODE(INC, "++",  IncDec)
OPCODE(DEC, "--",  IncDec)
OPCODE(ADDR,    "&",                    Address)

OPCODE(MOV, "=",  Move)
OPCODE(JMP,     "jmp",                  Jump)
OPCODE(CALL,    "call",                 Call)
OPCODE(RET, "ret", Return)
OPCODE(NOP,     "NOP",                  NOP)
